package by.diomov.newsportal.controller;

public enum CommandName {
	REGISTRATION, AUTHORIZATION, REGISTRATION_NEW_USER, UNKNOWN_COMMAND, GO_TO_MAIN_PAGE, CHANGE_LOCAL, LOG_OUT,
	SIGN_IN, ADD_NEWS, GO_TO_ADD_NEWS_PAGE, UPDATE_NEWS, GO_TO_UPDATE_NEWS_PAGE, DELETE_NEWS, GO_TO_READ_NEWS_PAGE,
	GO_TO_ADD_COMMENT_PAGE, ADD_COMMENT, GO_TO_READ_COMMENTS_PAGE, READ_COMMENTS, GO_TO_USER_PROFILE, CHANGE_PASSWORD,
	GO_TO_CHANGE_PASSWORD, ADD_NEWS_TO_FAVOURITE, GO_TO_FAVOURITE_NEWS_PAGE, DELETE_NEWS_FROM_FAVOURITE
}